baseURL = "https://dindinet.github.io/sawmill-starter/"
languageCode = "en-us"
theme = "sawmill"
title = "Sawmill"
cloudinary_url = "https://res.cloudinary.com/maxgoldhouse/image/upload/"
[Author]
name = "DJ Walker"
[[menu.main]]
name = "View on Github"
url = "https://dindinet.github.io/sawmill-starter/"
weight = 1
[[menu.main]]
name = "The Max of Gold House"
url = "https://www.maxgoldhouse.com"
weight = 1
[params]
logo = "https://dindinet.github.io/sawmill-starter/logo.svg"
