baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill"
title = "Sawmill"
[Author]
name = "DJ Walker"
[[menu.main]]
name = "The Max of Gold House"
url = "https://www.maxgoldhouse.com"
weight = 1
[[menu.main]]
name = "View on Github"
url = "https://github.com/dwalkr/sawmill"
weight = 1
[params]
logo = "/logo.svg"
